# Generated by Django 3.1.2 on 2020-10-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(),
        ),
    ]
